In [3]:
import numpy as np

In [6]:
test = np.load("../c++/1dvector.npy")
print(test)

[1. 2. 3. 4. 5. 6.]


In [15]:
test = np.load("../c++/2dvector.npy")
print(test)

'''
残念ながら2dversionはあまり安定していない．以下のようになる時がある．
[[ 1.          2.        ]
 [ 2.          3.        ]
 [ 3.          4.        ]
 [ 4.          5.        ]
 [15.38969994  0.        ]
 [ 0.          0.        ]]


[[ 1.          2.        ]
 [ 2.          3.        ]
 [ 3.          4.        ]
 [ 4.          5.        ]
 [15.38969994  0.        ]
 [ 0.          0.        ]]


In [18]:
test = np.load("../c++/1dvector_v2.npy")
print(test)

[[1. 2. 3. 4. 5. 6.]]


In [21]:
test = np.load("../c++/2dvector_v2.npy")
print(test)

[[ 1. 11.]
 [ 2. 12.]
 [ 3. 13.]
 [ 4. 14.]
 [ 5. 15.]
 [ 6. 16.]]


In [24]:
test = np.load("../c++/descs_ch.npy")
print(np.shape(test))

(174, 288)


In [36]:
test_c = np.load("../c++/descs_ch5.npy")
test_py =np.loadtxt("../../test/pg/bulk_test/Descs_ch_5.csv",delimiter=",")
sub = test_c-test_py
print(np.shape(sub))
print(np.argmax(test_c[0]))
# print(test_py[0][0])

(180, 288)
72
