In [3]:
import numpy as np

In [6]:
test = np.load("../c++/1dvector.npy")
print(test)

[1. 2. 3. 4. 5. 6.]


In [15]:
test = np.load("../c++/2dvector.npy")
print(test)

'''
残念ながら2dversionはあまり安定していない．以下のようになる時がある．
[[ 1.          2.        ]
 [ 2.          3.        ]
 [ 3.          4.        ]
 [ 4.          5.        ]
 [15.38969994  0.        ]
 [ 0.          0.        ]]


[[ 1.          2.        ]
 [ 2.          3.        ]
 [ 3.          4.        ]
 [ 4.          5.        ]
 [15.38969994  0.        ]
 [ 0.          0.        ]]


In [18]:
test = np.load("../c++/1dvector_v2.npy")
print(test)

[[1. 2. 3. 4. 5. 6.]]


In [21]:
test = np.load("../c++/2dvector_v2.npy")
print(test)

[[ 1. 11.]
 [ 2. 12.]
 [ 3. 13.]
 [ 4. 14.]
 [ 5. 15.]
 [ 6. 16.]]


In [24]:
test = np.load("../c++/descs_ch.npy")
print(np.shape(test))

(174, 288)


In [12]:
#
# ! mol_bc.xyzに違いがあるかを確認する．
import ase.io
import numpy as np
for i in range(10):
    test_c=ase.io.read("../c++/test_atoms"+str(i)+".xyz")
    test_py=ase.io.read("../../test/pg/bulk_test/mol_bc.xyz",index=i)
    sub = test_c.get_positions()-test_py.get_positions()
    print(np.max(sub))

4.972999999885985e-05
4.984999999990691e-05
4.998000000000502e-05
4.986000000073432e-05
4.988000000061277e-05
4.990000000049122e-05
4.993999999847176e-05
4.990000000049122e-05
4.9889999999663814e-05
4.994000000024812e-05


In [4]:
#
# ! CPml.pyとの違いがあるかを確認する．
import numpy as np
for i in range(10):
    test_c = np.load("../c++/build/descs_ch"+str(i)+".npy")
    test_py =np.loadtxt("../../test/pg/bulk_test/Descs_ch_"+str(i)+".csv",delimiter=",")
    sub = test_c-test_py
    print(np.max(np.abs(sub)))
    # print(test_c[0])
    # print(test_py[0])

1.5751289161869408e-15
2.4424906541753444e-15
1.4710455076283324e-15
2.55351295663786e-15
3.1086244689504383e-15
2.4424906541753444e-15
1.5543122344752192e-15
1.5543122344752192e-15
2.6645352591003757e-15
3.3306690738754696e-15


In [7]:
#
# ! CPml.pyとの違いがあるかを確認する．
import numpy as np
for i in range(10):
    test_c = np.load("../c++/build/descs_co"+str(i)+".npy")
    test_py =np.loadtxt("../../test/pg/bulk_test/Descs_co_"+str(i)+".csv",delimiter=",")
    sub = test_c-test_py
    print(np.max(np.abs(sub)))
    # print(test_c[0])
    # print(test_py[0])

1.4432899320127035e-15
4.440892098500626e-16
4.996003610813204e-16
4.440892098500626e-16
4.440892098500626e-16
8.881784197001252e-16
7.771561172376096e-16
7.771561172376096e-16
8.881784197001252e-16
8.881784197001252e-16


In [8]:
#
# ! CPml.pyとの違いがあるかを確認する．
import numpy as np
for i in range(10):
    test_c = np.load("../c++/build/descs_oh"+str(i)+".npy")
    test_py =np.loadtxt("../../test/pg/bulk_test/Descs_oh_"+str(i)+".csv",delimiter=",")
    sub = test_c-test_py
    print(np.max(np.abs(sub)))
    # print(test_c[0])
    # print(test_py[0])

2.220446049250313e-15
1.7763568394002505e-15
9.992007221626409e-16
1.7763568394002505e-15
8.881784197001252e-16
1.3322676295501878e-15
1.797173521111972e-15
1.7763568394002505e-15
1.1102230246251565e-15
1.5543122344752192e-15


In [19]:
#
# ! CPml.pyとの違いがあるかを確認する@ccボンド
# CCボンドの場合は，先頭のccについてソートの関係でpythonとcで違いがある．
import numpy as np
for i in range(1):
    test_c = np.load("../c++/descs_cc"+str(i)+".npy")
    test_py =np.loadtxt("../../test/pg/bulk_test/Descs_cc_"+str(i)+".csv",delimiter=",")
    sub = test_c-test_py
    print(np.max(np.abs(sub)))
    print(test_c[7][:8])
    print(test_py[7][:8])
    
    # print(test_py[0])

2.6701366928949386
[ 1.29408745  0.25489755  0.55037218 -1.14314479  1.29408745 -0.25489755
 -0.55037218  1.14314479]
[ 1.29408745 -0.25489755 -0.55037218  1.14314479  1.29408745  0.25489755
  0.55037218 -1.14314479]


In [9]:
#
# ! CPml.pyとの違いがあるかを確認する．
import numpy as np
for i in range(10):
    test_c = np.load("../c++/build/descs_o"+str(i)+".npy")
    test_py =np.loadtxt("../../test/pg/bulk_test/Descs_o_"+str(i)+".csv",delimiter=",")
    sub = test_c-test_py
    print(np.max(np.abs(sub)))
    # print(test_c[0])
    # print(test_py[0])

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
