In [ ]:
# 実際にXMLファイルからエネルギーを読む．


import xml.etree.ElementTree as ET 

# XMLファイルを解析
tree = ET.parse("rutile224_scph_bubble3_2.xml") 

# XMLを取得
root = tree.getroot()

In [ ]:
print(root.attrib)

In [ ]:
for child in root:
    print(child.tag)
    print(child.attrib)

# xmlファイルの単位について
## これについてはxmlではなくfcsファイルに書いてある．

In [54]:

# 座標の差分を計算
# !! 注意 vaspはもともとAngstrom単位だが，ALAMODEに入れるのにbohr単位にする必要あり．
def calc_subtract(i, dir):
    import ase.io
    import numpy as np
    
    # in angstrom
    primitive=ase.io.read(dir+"POSCAR").get_positions()
    #
    displace=ase.io.read(dir+"disp"+i+".POSCAR").get_positions()
    # ang to bohr
    subtract=(displace-primitive)*1.8897259886
    print("i =  ", i)
    # print(subtract)
    # print(" ")
    np.savetxt(dir+"disp"+str(i)+".txt", subtract, header="6 96", comments="")
    return subtract

# calc_subtract("01", "disp_POSCAR/")

In [55]:
import subprocess
# dir="disp_POSCAR/A2u_0_4/"
# dir="disp_POSCAR/trial_E1u/"
# dir="disp_POSCAR/trial_Eg/"
# dir="disp_POSCAR/A2u_0_0.5/"
dir="disp_POSCAR/A2u_0_2/"


import numpy as np
for i in np.arange(1,6):
    i=str(i).zfill(2)
    calc_subtract(i, dir)
    filename=dir+"disp"+str(i)+".txt"
    cmd = "./displace_energy TiO2224_anharm.xml "+filename  #<=ここにコマンドを当てはめる
    process = (subprocess.Popen(cmd, stdout=subprocess.PIPE,
                           shell=True).communicate()[0]).decode('utf-8')
    
    print(process)#何かしらの処理



i =   01
 ifs_displace 6 96
0 0 0

i =   02
 ifs_displace 6 96
0.000391279 0.000394173 0.000394172

i =   03
 ifs_displace 6 96
0.00156511 0.00161142 0.00161139

i =   04


KeyboardInterrupt: 

In [20]:
# 0.25877026576 Ang = 4.000000 (u^{1/2} ang
# 0.04085846301 Ang = 0.631579 (u^{1/2} ang

test=np.loadtxt("disp_POSCAR/A2u_0_0.5/output2.txt")
disp=np.linspace(0,9.143811427298992323e-02,20).reshape(20,1)
print(test)
print(disp)
test2=np.concatenate([disp, test],axis=1)
print(test2)
np.savetxt("disp_POSCAR/A2u_0_0.5/output3.txt", test2)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00000000e+00 2.44548817e-05 2.44661744e-05 2.44661744e-05]
 [2.00000000e+00 9.78196629e-05 9.80006187e-05 9.80006187e-05]
 [3.00000000e+00 2.20093935e-04 2.21009599e-04 2.21009599e-04]
 [4.00000000e+00 3.91278107e-04 3.94173400e-04 3.94172039e-04]
 [5.00000000e+00 6.11373403e-04 6.18438842e-04 6.18436121e-04]
 [6.00000000e+00 8.80377102e-04 8.95029078e-04 8.95022275e-04]
 [7.00000000e+00 1.19829056e-03 1.22543529e-03 1.22541897e-03]
 [8.00000000e+00 1.56511787e-03 1.61141806e-03 1.61139085e-03]
 [9.00000000e+00 1.98085358e-03 2.05501824e-03 2.05495021e-03]
 [1.00000000e+01 2.44548817e-03 2.55855152e-03 2.55840186e-03]
 [1.10000000e+01 2.95904885e-03 3.12457577e-03 3.12431726e-03]
 [1.20000000e+01 3.52150841e-03 3.75593459e-03 3.75551281e-03]
 [1.30000000e+01 4.13288045e-03 4.45578448e-03 4.45509059e-03]
 [1.40000000e+01 4.79316498e-03 5.22747247e-03 5.22641122e-03]
 [1.50000000e+01 5.50236199e-03 6.07469928e-03 6.073080

In [19]:
# 0.25877026576 Ang = 4.000000 (u^{1/2} ang
# 0.04085846301 Ang = 0.631579 (u^{1/2} ang

dir="disp_POSCAR/A2u_0_0.5/"
dir="disp_POSCAR/trial_Eg_3/"
dir="disp_POSCAR/trial_E1u_3/"
dir="disp_POSCAR/trial_E1u_4/"
dir="disp_POSCAR/trial_Eg_4/"
dir="disp_POSCAR/trial_A2u_4/"


max_disp=9.143681506200958264e-02 #A2u
max_disp=1.670328939805949264e-01 #Eg
max_disp=7.187048514124315390e-02 #E1u
max_disp=1.437409702824577612e-02 #E1u_4
max_disp=3.340657879612024539e-02
max_disp=1.828736301240079659e-02

import numpy as np
test=np.loadtxt(dir+"vasp.txt")
disp=np.linspace(0,max_disp,20).reshape(20,1)
# print(test[0][2])
print(disp)

offset=test[0][1] #displace=0でのenergy

for i in range(20):
    print("i", i)
    test[i][1]=test[i][1]-offset
    # print(test[i][1]+test[0][1])

test2=np.concatenate([disp, test],axis=1)
print(test2)
np.savetxt(dir+"vasp2.txt", test2)


[[0.        ]
 [0.00096249]
 [0.00192499]
 [0.00288748]
 [0.00384997]
 [0.00481246]
 [0.00577496]
 [0.00673745]
 [0.00769994]
 [0.00866244]
 [0.00962493]
 [0.01058742]
 [0.01154991]
 [0.01251241]
 [0.0134749 ]
 [0.01443739]
 [0.01539988]
 [0.01636238]
 [0.01732487]
 [0.01828736]]
i 0
i 1
i 2
i 3
i 4
i 5
i 6
i 7
i 8
i 9
i 10
i 11
i 12
i 13
i 14
i 15
i 16
i 17
i 18
i 19
[[0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [9.62492790e-04 2.00000000e+00 9.59999994e-07]
 [1.92498558e-03 3.00000000e+00 3.83000000e-06]
 [2.88747837e-03 4.00000000e+00 8.60999999e-06]
 [3.84997116e-03 5.00000000e+00 1.53100000e-05]
 [4.81246395e-03 6.00000000e+00 2.39400000e-05]
 [5.77495674e-03 7.00000000e+00 3.44800000e-05]
 [6.73744953e-03 8.00000000e+00 4.69600000e-05]
 [7.69994232e-03 9.00000000e+00 6.13600000e-05]
 [8.66243511e-03 1.00000000e+01 7.77100000e-05]
 [9.62492790e-03 1.10000000e+01 9.60000000e-05]
 [1.05874207e-02 1.20000000e+01 1.16250000e-04]
 [1.15499135e-02 1.30000000e+01 1.38450000e-04]
 [1.2

In [14]:
# output.txtにdisplacementの大きさを追加する.


dir="disp_POSCAR/A2u_0_0.5/"
dir="disp_POSCAR/trial_Eg_3/"
# dir="disp_POSCAR/trial_E1u_3/"

max_disp=9.143681506200958264e-02 #A2u
max_disp=1.670328939805949264e-01 #Eg
# max_disp=7.187048514124315390e-02 #E1u

import numpy as np
test=np.loadtxt(dir+"output.txt")
disp=np.linspace(0,max_disp,20).reshape(20,1)
# print(test[0][2])
print(disp)

test2=np.concatenate([disp, test],axis=1)
print(test2)
np.savetxt(dir+"output2.txt", test2)



[[0.        ]
 [0.0087912 ]
 [0.01758241]
 [0.02637361]
 [0.03516482]
 [0.04395602]
 [0.05274723]
 [0.06153843]
 [0.07032964]
 [0.07912084]
 [0.08791205]
 [0.09670325]
 [0.10549446]
 [0.11428566]
 [0.12307687]
 [0.13186807]
 [0.14065928]
 [0.14945048]
 [0.15824169]
 [0.16703289]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.0087912  0.00026538 0.00026538 0.00026539 0.00026539 0.00026539]
 [0.01758241 0.00106154 0.00106154 0.00106155 0.00106155 0.00106156]
 [0.02637361 0.00238846 0.00238846 0.00238854 0.00238854 0.00238858]
 [0.03516482 0.00424616 0.00424616 0.00424639 0.00424639 0.00424665]
 [0.04395602 0.00663462 0.00663462 0.0066352  0.0066352  0.00663616]
 [0.05274723 0.00955385 0.00955385 0.00955506 0.00955506 0.00955794]
 [0.06153843 0.01300385 0.01300385 0.0130061  0.0130061  0.01301335]
 [0.07032964 0.01698462 0.01698462 0.01698845 0.01698845 0.01700461]
 [0.07912084 0.02149616 0.02149616 0.0215023  0.0215023  0.02153505]
 [0.08791205 0.02653847 0.026

In [9]:
x=1.924985580252833173e-02
y=4.242050000001995613e-03

print(y/x/x)

11.447768064020481


In [40]:
vasp=np.loadtxt("disp_POSCAR/A2u_merged_analysis/vasp_merged.txt")
alm =np.loadtxt("disp_POSCAR/A2u_merged_analysis/merged.txt")
print(vasp[:,1])
print(alm)
test2=np.concatenate([alm, vasp[:,1].reshape(40,1)],axis=1)
print(test2)
np.savetxt("disp_POSCAR/A2u_merged_analysis/merged2.txt",test2)


[0.0000000e+00 2.3910000e-05 9.5910000e-05 2.1672000e-04 3.8034000e-04
 6.0255000e-04 8.7799000e-04 1.2089100e-03 1.5979700e-03 2.0480800e-03
 2.5625000e-03 3.1449500e-03 3.7995100e-03 4.5307200e-03 5.3435100e-03
 6.2431300e-03 7.2351000e-03 8.3254500e-03 9.5205600e-03 1.0834220e-02
 0.0000000e+00 3.8034000e-04 1.5979700e-03 3.7995100e-03 7.2351000e-03
 1.2259320e-02 1.9297890e-02 2.8893570e-02 4.1672080e-02 5.8319300e-02
 7.9585790e-02 1.0628801e-01 1.3929015e-01 1.7950403e-01 2.2787799e-01
 2.8538943e-01 3.5303295e-01 4.3182617e-01 5.2280673e-01 6.2701781e-01]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.81253233e-03 2.44548817e-05 2.44661744e-05 2.44661744e-05]
 [9.62506466e-03 9.78196629e-05 9.80006187e-05 9.80006187e-05]
 [1.44375970e-02 2.20093935e-04 2.21009599e-04 2.21009599e-04]
 [1.92501293e-02 3.91278107e-04 3.94173400e-04 3.94172039e-04]
 [2.40626617e-02 6.11373403e-04 6.18438842e-04 6.18436121e-04]
 [2.88751940e-02 8.80377102e-04 8.95029078e-04 8.9502

In [41]:
import numpy as np
born=np.loadtxt("borninfo_r2SCAN").reshape(6,3,3)
#print(born)
print("")
#
#print(np.sum(born,axis=0))
print("")
born=born-np.sum(born,axis=0)/6
print(born)



[[[-13.75399883   8.76272988   0.        ]
  [  8.76272988 -13.75399883   0.        ]
  [  0.           0.           3.65933343]]

 [[-13.75399883  -8.76272988   0.        ]
  [ -8.76272988 -13.75399883   0.        ]
  [  0.           0.           3.65933343]]

 [[  6.87699941   1.77130322   0.        ]
  [  1.77130322   6.87699941   0.        ]
  [  0.           0.          -1.82966672]]

 [[  6.87699941   1.77130322   0.        ]
  [  1.77130322   6.87699941   0.        ]
  [  0.           0.          -1.82966672]]

 [[  6.87699941  -1.77130322   0.        ]
  [ -1.77130322   6.87699941   0.        ]
  [  0.           0.          -1.82966672]]

 [[  6.87699941  -1.77130322   0.        ]
  [ -1.77130322   6.87699941   0.        ]
  [  0.           0.          -1.82966672]]]
